//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.BLL.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApi.BLL.Resources.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action blocked.
        /// </summary>
        public static string ActionBlocked {
            get {
                return ResourceManager.GetString("ActionBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advert is blocked.
        /// </summary>
        public static string AdvertIsBlocked {
            get {
                return ResourceManager.GetString("AdvertIsBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup creatin error: {0}.
        /// </summary>
        public static string BackupCreatinError {
            get {
                return ResourceManager.GetString("BackupCreatinError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password is not valid.
        /// </summary>
        public static string CurrentPasswordIsNotValid {
            get {
                return ResourceManager.GetString("CurrentPasswordIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error database restore: {0}.
        /// </summary>
        public static string DataBaseRestoreError {
            get {
                return ResourceManager.GetString("DataBaseRestoreError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An account with this email already exists.
        /// </summary>
        public static string EmailAlreadyExist {
            get {
                return ResourceManager.GetString("EmailAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adverts Ids is not be empty.
        /// </summary>
        public static string EmptyAdvertIds {
            get {
                return ResourceManager.GetString("EmptyAdvertIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error authorized user.
        /// </summary>
        public static string ErrorAthorizedUser {
            get {
                return ResourceManager.GetString("ErrorAthorizedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error open backup file.
        /// </summary>
        public static string ErrorOpenBackupFile {
            get {
                return ResourceManager.GetString("ErrorOpenBackupFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Darabase restore error: {0}.
        /// </summary>
        public static string ErrorRestoreDataBase {
            get {
                return ResourceManager.GetString("ErrorRestoreDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error starting pg_dump process..
        /// </summary>
        public static string ErrorStarPGDump {
            get {
                return ResourceManager.GetString("ErrorStarPGDump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error starting pg_restore process.
        /// </summary>
        public static string ErrorStartPGRestore {
            get {
                return ResourceManager.GetString("ErrorStartPGRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image sizes not initializing.
        /// </summary>
        public static string ImageSizesInitError {
            get {
                return ResourceManager.GetString("ImageSizesInitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error read image sizes.
        /// </summary>
        public static string ImageSizesReadError {
            get {
                return ResourceManager.GetString("ImageSizesReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid admin message id.
        /// </summary>
        public static string InvalidAdminMessageId {
            get {
                return ResourceManager.GetString("InvalidAdminMessageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid advert id.
        /// </summary>
        public static string InvalidAdvertId {
            get {
                return ResourceManager.GetString("InvalidAdvertId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid area ref.
        /// </summary>
        public static string InvalidAreaRef {
            get {
                return ResourceManager.GetString("InvalidAreaRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid backup file name.
        /// </summary>
        public static string InvalidBackupFileName {
            get {
                return ResourceManager.GetString("InvalidBackupFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid category id.
        /// </summary>
        public static string InvalidCategoryId {
            get {
                return ResourceManager.GetString("InvalidCategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid chat id.
        /// </summary>
        public static string InvalidChatId {
            get {
                return ResourceManager.GetString("InvalidChatId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid chat messeges ids.
        /// </summary>
        public static string InvalidChatMessegesIds {
            get {
                return ResourceManager.GetString("InvalidChatMessegesIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation data error.
        /// </summary>
        public static string InvalidConfirmationData {
            get {
                return ResourceManager.GetString("InvalidConfirmationData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid filter creation model data.
        /// </summary>
        public static string InvalidFilterCreationModelData {
            get {
                return ResourceManager.GetString("InvalidFilterCreationModelData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid filter id.
        /// </summary>
        public static string InvalidFilterId {
            get {
                return ResourceManager.GetString("InvalidFilterId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid filter value id.
        /// </summary>
        public static string InvalidFilterValueId {
            get {
                return ResourceManager.GetString("InvalidFilterValueId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already has current locked status.
        /// </summary>
        public static string InvalidLockedOperation {
            get {
                return ResourceManager.GetString("InvalidLockedOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login or password.
        /// </summary>
        public static string InvalidLoginData {
            get {
                return ResourceManager.GetString("InvalidLoginData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid parent category id.
        /// </summary>
        public static string InvalidParentCategoryId {
            get {
                return ResourceManager.GetString("InvalidParentCategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect password entered.
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid region ref.
        /// </summary>
        public static string InvalidRegionRef {
            get {
                return ResourceManager.GetString("InvalidRegionRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid reser password data.
        /// </summary>
        public static string InvalidResetPasswordData {
            get {
                return ResourceManager.GetString("InvalidResetPasswordData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid role name.
        /// </summary>
        public static string InvalidRole {
            get {
                return ResourceManager.GetString("InvalidRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid settlement id.
        /// </summary>
        public static string InvalidSettlementId {
            get {
                return ResourceManager.GetString("InvalidSettlementId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid settlement ref.
        /// </summary>
        public static string InvalidSettlementRef {
            get {
                return ResourceManager.GetString("InvalidSettlementRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid token.
        /// </summary>
        public static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user email.
        /// </summary>
        public static string InvalidUserEmail {
            get {
                return ResourceManager.GetString("InvalidUserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user id.
        /// </summary>
        public static string InvalidUserId {
            get {
                return ResourceManager.GetString("InvalidUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error read JWT setting.
        /// </summary>
        public static string JwtSettingsReadError {
            get {
                return ResourceManager.GetString("JwtSettingsReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account deletion denied..
        /// </summary>
        public static string LastAdminDeleteBlock {
            get {
                return ResourceManager.GetString("LastAdminDeleteBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple refresh.
        /// </summary>
        public static string MultipleRefresh {
            get {
                return ResourceManager.GetString("MultipleRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New post data update error.
        /// </summary>
        public static string NewPostDataUpdateError {
            get {
                return ResourceManager.GetString("NewPostDataUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New post request error.
        /// </summary>
        public static string NewPostRequestError {
            get {
                return ResourceManager.GetString("NewPostRequestError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid adverts found.
        /// </summary>
        public static string NoValidAdverts {
            get {
                return ResourceManager.GetString("NoValidAdverts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reCapthca validation error.
        /// </summary>
        public static string ReCapthcaValidationError {
            get {
                return ResourceManager.GetString("ReCapthcaValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User creation error.
        /// </summary>
        public static string UserCreateError {
            get {
                return ResourceManager.GetString("UserCreateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User remove error.
        /// </summary>
        public static string UserRemoveError {
            get {
                return ResourceManager.GetString("UserRemoveError", resourceCulture);
            }
        }
    }
}
