//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.BLL.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApi.BLL.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been deleted by the site administrator.
        /// </summary>
        public static string AccountDeleted {
            get {
                return ResourceManager.GetString("AccountDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is locked.
        /// </summary>
        public static string AccountLocked {
            get {
                return ResourceManager.GetString("AccountLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account removed.
        /// </summary>
        public static string AccountRemoved {
            get {
                return ResourceManager.GetString("AccountRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been unlocked.
        /// </summary>
        public static string AccountUnlocked {
            get {
                return ResourceManager.GetString("AccountUnlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The admin has deleted your advert.&quot;{0}&quot;..
        /// </summary>
        public static string AdminDeleteAdvert {
            get {
                return ResourceManager.GetString("AdminDeleteAdvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The admin has locked your advert &quot;{0}&quot;..
        /// </summary>
        public static string AdminLockAdvert {
            get {
                return ResourceManager.GetString("AdminLockAdvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your advert has been deleted..
        /// </summary>
        public static string AdvertDeleted {
            get {
                return ResourceManager.GetString("AdvertDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due to violation of the rules and non-compliance with the site&apos;s policy..
        /// </summary>
        public static string AdvertDeletedDefault {
            get {
                return ResourceManager.GetString("AdvertDeletedDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your advert has been added to favorites..
        /// </summary>
        public static string AdvertInFavorites {
            get {
                return ResourceManager.GetString("AdvertInFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advert is locked.
        /// </summary>
        public static string AdvertLocked {
            get {
                return ResourceManager.GetString("AdvertLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Areas - {0}.
        /// </summary>
        public static string AreasCount {
            get {
                return ResourceManager.GetString("AreasCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start areas update ....
        /// </summary>
        public static string AreasUpdate {
            get {
                return ResourceManager.GetString("AreasUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup successfully created..
        /// </summary>
        public static string BackupCreated {
            get {
                return ResourceManager.GetString("BackupCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup process has started..
        /// </summary>
        public static string BackupStart {
            get {
                return ResourceManager.GetString("BackupStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database update succeeded!.
        /// </summary>
        public static string DataBaseUpdateSucceeded {
            get {
                return ResourceManager.GetString("DataBaseUpdateSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email confirmation.
        /// </summary>
        public static string EmailConfirmation {
            get {
                return ResourceManager.GetString("EmailConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email is not confirmed. Please check your inbox for confirmation..
        /// </summary>
        public static string EmailNotConfirmed {
            get {
                return ResourceManager.GetString("EmailNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been locked due to too many unsuccessful login attempts.
        /// </summary>
        public static string FailedLoginAttempts {
            get {
                return ResourceManager.GetString("FailedLoginAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For an indefinite period.
        /// </summary>
        public static string Indefinitely {
            get {
                return ResourceManager.GetString("Indefinitely", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked until.
        /// </summary>
        public static string LockedUntil {
            get {
                return ResourceManager.GetString("LockedUntil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Post data successfully updated !!!.
        /// </summary>
        public static string NPUpdateCompleted {
            get {
                return ResourceManager.GetString("NPUpdateCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reCaptcha validation error.
        /// </summary>
        public static string reCaptchaValidationError {
            get {
                return ResourceManager.GetString("reCaptchaValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regions - {0}.
        /// </summary>
        public static string RegionsCount {
            get {
                return ResourceManager.GetString("RegionsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start regions update .....
        /// </summary>
        public static string RegionsUpdate {
            get {
                return ResourceManager.GetString("RegionsUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start settlements update ....
        /// </summary>
        public static string SettlemensUpdate {
            get {
                return ResourceManager.GetString("SettlemensUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settlements - {0}.
        /// </summary>
        public static string SettlementsCount {
            get {
                return ResourceManager.GetString("SettlementsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User &quot;{0}&quot; added your advert &quot;{1}&quot; to favorites..
        /// </summary>
        public static string UserAddedToFavorites {
            get {
                return ResourceManager.GetString("UserAddedToFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User &quot;{0}&quot; bought your advert &quot;{1}&quot;.
        /// </summary>
        public static string UserBoughtAdvert {
            get {
                return ResourceManager.GetString("UserBoughtAdvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User  bought your advert.
        /// </summary>
        public static string UserBouth {
            get {
                return ResourceManager.GetString("UserBouth", resourceCulture);
            }
        }
    }
}
